### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by prein** [SumoLogic/sumologic-solution-templates#41]
Hi, The link in the Readme:  https://help.sumologic.com/Solutions/AWS_Observability_Solution/About_the_AWS_Observability_Solution
leads (after a few 302s and a login) to a whitepage with "You do not have permission to view this page." message in a red box.

**Comment by astencel-sumo** [comment]
Thanks for reporting this @prein!

This link should probably be replaced with https://help.sumologic.com/Observability_Solution/AWS_Observability_Solution.

Let me create a quick PR for this.

**Comment by astencel-sumo** [comment]
Fixed this and a couple other links in #42.
